// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: add_record.sql

package database

import (
	"context"
	"time"
)

const createRecord = `-- name: CreateRecord :one
INSERT INTO records_2026 (
        record_date,
        record_title,
        record_type,
        updated_at
    )
VALUES ($1, $2, $3, NOW())
RETURNING id, record_date, record_title, record_type, updated_at
`

type CreateRecordParams struct {
	RecordDate  time.Time
	RecordTitle string
	RecordType  string
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (Records2026, error) {
	row := q.db.QueryRowContext(ctx, createRecord, arg.RecordDate, arg.RecordTitle, arg.RecordType)
	var i Records2026
	err := row.Scan(
		&i.ID,
		&i.RecordDate,
		&i.RecordTitle,
		&i.RecordType,
		&i.UpdatedAt,
	)
	return i, err
}

const resetRecords = `-- name: ResetRecords :exec
DELETE FROM records_2026
`

func (q *Queries) ResetRecords(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetRecords)
	return err
}
