// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"
)

type Records2026 struct {
	ID          int32
	RecordDate  time.Time
	RecordTitle string
	RecordType  string
	UpdatedAt   time.Time
}
